### ISSUE TITLE
Can you send a verson of mnist dataset for amsoftmax, I modify a verson but when s=30 and m=0.4 it not converge and loss is also 16.811

### ISSUE THREAD

**Issue by FlyEgle** [happynear/AMSoftmax#11]
I push my code here 

![image](https://user-images.githubusercontent.com/26165705/38620136-51c2d8c0-3dd0-11e8-9975-f4cddb0fb7ce.png)
![image](https://user-images.githubusercontent.com/26165705/38620153-5fb53f54-3dd0-11e8-8a95-9abe26fe72b7.png)
5 of 10 epoch
![image](https://user-images.githubusercontent.com/26165705/38620059-29b0ab5a-3dd0-11e8-9a14-baa7efcdefef.png)

**Comment by happynear** [comment]
For MNIST, I recommend to use `s=10`.
