### ISSUE TITLE
draw_sphere

### ISSUE THREAD

**Issue by xiaosuzhang** [happynear/AMSoftmax#13]
您好，我想得到不同损失函数在mnist数据集上球面分布的图，自己使用不同的loss function去训练，得到的相应的模型图，但是还是无法画图？您的那个jet.mat文件是如何生成的？谢谢

**Comment by happynear** [comment]
https://github.com/happynear/AMSoftmax/tree/master/draw/draw_sphere
看这里的说明。

**Comment by xiaosuzhang** [comment]
您好，我训练的基于A-softmax损失函数的模型，但是画图的时候matlab直接闪退？？？

**Comment by happynear** [comment]
闪退的话看看当前目录下log文件夹里的日志，根据报错来修改。
