### ISSUE TITLE
CASIA-Webface dataset download link

### ISSUE THREAD

**Issue by Yangel-hide** [happynear/AMSoftmax#14]
@happynear I can't get any download link about CASIA-Webface, neither cleaned CASIA Dataset nor dirty.
The official download link and Baiduyun links that I found on the Internet cannot be accessed now，Can you give me a download link, thank you!

**Comment by xisi789** [comment]
链接：https://pan.baidu.com/s/1cZqvicKzp_O3KXgmHIwFIw 密码：e5br

**Comment by Yangel-hide** [comment]
@xisi789 Thank you very much！

**Comment by Chanbluky** [comment]
> 链接：https://pan.baidu.com/s/1cZqvicKzp_O3KXgmHIwFIw 密码：e5br

could you share the link again? it is out of date. thanks!

**Comment by soumendra** [comment]
The link seems to be dead, possible for anyone to share it again? Thanks.

**Comment by visionjo** [comment]
https://drive.google.com/uc?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz&export=download

**Comment by Coderx7** [comment]
@visionjo : Is this the washed up(cleaned) version or the original casia webface? 
Thanks a lot in advance

**Comment by randanachet** [comment]
hi, please could you share the link again? and thanks in advance.

**Comment by jaimerodric** [comment]
Yes please share it if possible

**Comment by qwe12345113** [comment]
Could you share the google drive link, please? Thanks.
