### ISSUE TITLE
The way of using AMSoftmax

### ISSUE THREAD

**Issue by Anguliachao** [happynear/AMSoftmax#16]
Dear AMSoftmax team,
    Thanks for the great work, I've checked out your paper and  prepare to try my owndata on the repo, however I'm a bit confused, would you mind telling me the relation between Amsoftmax and Sphereface? I noticed AMSoftmax seems to be the latest result on your experiment, but there's no many instructions of manipulation . As far as I recognized ,  should the only difference between Sphereface and AMSoftmax be the prototxt file? besides I can not only obtain AMSoftmax repo, but to keep Sphereface repo and follow the steps to train?

**Comment by happynear** [comment]
Yes, follow the steps of SphereFace to train but using the Caffe and prototxt files provided in this repo.

**Comment by Anguliachao** [comment]
Many thanks !

**Comment by happynear** [comment]
[face_deploy_20.zip](https://github.com/happynear/AMSoftmax/files/2200896/face_deploy_20.zip)
Try this deploy file?
