### ISSUE TITLE
iter_size问题

### ISSUE THREAD

**Issue by wzj5133329** [happynear/AMSoftmax#17]
你好，对于slover配置文件iter_size参数我在网上查了相关资料，caffe官方并没有这个参数的说明，我的问题是，如果设置这个参数相当于调整了batch_size,那么迭代次数是不是应该减少呢，因为我设置了这个参数为n后，训练的速度相应的变慢了n倍，求解答

**Comment by ujsyehao** [comment]
caffe的mini_batch_size = sub_batch_size * iter_size, 一次iteration就是一个mini_batch_size, 比如batch size是20, iter_size是2, mini_batch_size是40, 迭代次数相应的就减少了
