### ISSUE TITLE
CASIA-Webface dataset download link

### ISSUE THREAD

**Issue by saurav4098** [happynear/AMSoftmax#18]
Hi @xisi789 
Could you please again share the Casia webface database or Replay-Attack database for Face Anti Spoofing. I couldnot download it since the share file has expired

**Comment by KeyKy** [comment]
@Yangel-hide Could you share it again?

**Comment by Yangel-hide** [comment]
Baidu cloud:  链接: https://pan.baidu.com/s/1hQCOD4Kr66MOW0_PE8bL0w 密码: y3wj
google drive:  https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

**Comment by wuzuyuan** [comment]
@Yangel-hide Do you know how to download CASIA face anti-spoofing database? I tried several links, the URL was removed and there was no response.

**Comment by rafaelvareto** [comment]
I've searching for CASIA face anti-spoofing database. Haven't found yet.

**Comment by rafaelvareto** [comment]
I've been searching for CASIA face anti-spoofing database as well, but I haven't found yet.

**Comment by loubrys** [comment]
@Yangel-hide hi, I've been looking for casia face anti-spoofing database. do you know where or how can I get it?

**Comment by ihpannu** [comment]
> @Yangel-hide hi, I've been looking for casia face anti-spoofing database. do you know where or how can I get it?
This works - https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

**Comment by wangxiaolin007** [comment]
could anyone share casia face anti-spoofing database download link? thanks very much

**Comment by bcba25** [comment]
@wangxiaolin007 did u find any links ?

**Comment by ngoanpv** [comment]
Did anyone get the CASIA_FASD database? Please share with me: ngoanlearning@gmail.com 
Thanks

**Comment by engmubarak48** [comment]
> @Yangel-hide Do you know how to download CASIA face anti-spoofing database? I tried several links, the URL was removed and there was no response.

Did you find the data so far.

**Comment by Yangel-hide** [comment]
> > @Yangel-hide Do you know how to download CASIA face anti-spoofing database? I tried several links, the URL was removed and there was no response.
> 
> Did you find the data so far.

Sorry, I don't have

**Comment by mehboobillahi56** [comment]
Hey. Can anyone help me find the "Replay-Attack database for Face Anti Spoofing"?

**Comment by 610821216** [comment]
Could you share casia-webface again?

**Comment by ngoanpv** [comment]
@610821216 Ref https://github.com/happynear/AMSoftmax/issues/14#issuecomment-506990530

**Comment by 610821216** [comment]
@ngoanpv thanks

**Comment by mmxuan18** [comment]
> Baidu cloud: 链接: https://pan.baidu.com/s/1hQCOD4Kr66MOW0_PE8bL0w 密码: y3wj
> google drive: https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

i download from these link ,but no label file? @Yangel-hide

**Comment by 610821216** [comment]
Thank you !

Mlin <notifications@github.com>於 2020年6月1日 週一，下午6:39寫道：

**Comment by mesquita** [comment]
Anyone found the label file?

**Comment by m-vt** [comment]
> Hey. Can anyone help me find the "Replay-Attack database for Face Anti Spoofing"?

Hello, Did you find any database?

**Comment by Arvindia** [comment]
> 
> 
> Baidu cloud: 链接: https://pan.baidu.com/s/1hQCOD4Kr66MOW0_PE8bL0w 密码: y3wj
> google drive: https://drive.google.com/open?id=1Of_EVz-yHV7QVWQGihYfvtny9Ne8qXVz

@Yangel-hide official dataset claims 453453 images but this dataset has 773208 images. How?

**Comment by YingjingLu** [comment]
> Anyone found the label file?

The folder is the label. Each folder contains the same person shot in difference angles

**Comment by djaniak** [comment]
could anyone share working google drive link please? it is almost impossible to download something from baidu from outside China

**Comment by mdja** [comment]
Please share a working link to download casia webface dataset other than from baidu. I am not a chinesse and I can't download from there.

**Comment by RafikYacoub** [comment]
Please share a working link to download casia webface dataset. I need it asap for an academic project. 
Thank you

**Comment by FarzaneMojtabavi** [comment]
Hi, how can I download the CASIA-Webface dataset? All the sites listed above are blocked.

**Comment by Manohar-Anugu** [comment]
@Yangel-hide  Can you share updated link please. the drive link is down.

**Comment by kartikpodugu** [comment]
not a single link is working. how to download the database. please help.

**Comment by afm215** [comment]
You can find it on the insightface repo : https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_

**Comment by afm215** [comment]
be aware, that the final link underscore is not taken into account by the URL parser. If you just click on the link, it won't work. Check that you use the full URL

**Comment by mdja** [comment]
Thanks!. Finally a working link other than Baidu.

https://drive.google.com/file/d/1KxNCrXzln0lal3N4JiYl9cFOIhT78y1l/view


> be aware, that the final link underscore is not taken into account by the URL parser. If you just click on the link, it won't work. Check that you use the full URL

**Comment by afm215** [comment]
You 're welcome! Also the dataset is in .rec format, but it should be easy to find a script that convert back to png files using mxnet. (there is probably something within the insightface repository)
