### ISSUE TITLE
Compare AMSoftmax with ArcFace

### ISSUE THREAD

**Issue by basaltzhang** [happynear/AMSoftmax#19]
I didn't find any comparison between AMSoftmax and ArcFace on the internet, could you tell me your result ?

**Comment by happynear** [comment]
Well, in my experiments, `cos(theta+m)` is a little bit lower than `cos(theta) - m`. It's like `71.89%` vs `72.44%` on MegaFace, not too much lower. 

However, this result was gotten almost a year ago. Maybe I did something wrong at that time... I will do it again recently.
