### ISSUE TITLE
lfw准确率为99.73是如何得到的？使用的什么数据集！

### ISSUE THREAD

**Issue by jianbaba** [happynear/AMSoftmax#21]
您好，我有看您的实验都是使用的64层spereface结构进行训练的！那么请问，您有在别的结构上训练过么？我看arcface实用您的损失，arcface的结构能够达到99.7~99.8（仅适用vgg2或者ms）

**Comment by happynear** [comment]
我用的是20层的spherenet哎...目前用vgg2可以达到99.55%，估计64层能到99.7%吧。

**Comment by jianbaba** [comment]
@happynear 我是将am和cosface一起看的，这两篇的方法是一样的吧？还有就是我使用你给的网络结构去训练，相同的学习率和衰减方式，为什么准确率只有60多？我用的是face_train_test_auto.prototxt！！！您release的几个有什么差别么？

**Comment by happynear** [comment]
恩一样的。
你先别用auto，那个算法不成熟。你先用https://github.com/happynear/AMSoftmax/blob/master/prototxt/face_train_test.prototxt 试试。

**Comment by jianbaba** [comment]
@happynear 好的，还有就是您在casia和vgg2上都是用的一样的学习率，和衰减方式么？（ 0.1 and is divided by 10 at the 16K, 24K and 28K iterations. The training is finished at 30K iterations ）一共用了几个gpu呢？如果我在64层做实验，请问您有什么建议么？还是这样的学习率和衰减方式么？

**Comment by happynear** [comment]
vgg2上要把这些step扩大一倍。不管用几个gpu，保持batch size为256就行。

**Comment by jianbaba** [comment]
@happynear 好的，谢谢老哥！

**Comment by jianbaba** [comment]
@happynear 对了，测试的时候deploy选用这个face_deploy_mirror_normalize.prototxt？？还是直接把face_train_test.prototxt 改
（最后一层为？）
layer {
  name: "norm1"
  type: "Normalize"
  bottom: "fc5"
  top: "norm1"
}

**Comment by happynear** [comment]
face_deploy_mirror_normalize.prototxt这个比较好

**Comment by jianbaba** [comment]
@happynear 请问您推荐的这个prototxt原理是什么？图片为什么可以contact一起送入网络（是变成了6通道么？）之后为什么还能分开？
相比sphereface是将图片以及翻转图片分别送入网络，得到的特征进行串联！

**Comment by happynear** [comment]
https://github.com/happynear/NormFace/blob/master/MirrorFace.md
看这个。也是翻转图片。

**Comment by jianbaba** [comment]
@happynear 所以这个操作是代替了sphereface的做法是么？所以你这个最后不需要再去翻转后再输入到有镜像的网络了是么?直接用512维特征进行运算，而不是1024维度？

**Comment by happynear** [comment]
恩。

**Comment by jianbaba** [comment]
@happynear 您好，我按您的方式，64层网络结构（vgg2），按您说的的训练方式，准确率和之前一样，还是只有60%！您出过这种情况么？
