### ISSUE TITLE
Where is fc6 in face_train_test.prototxt?

### ISSUE THREAD

**Issue by Lin427** [happynear/AMSoftmax#26]
I only see the layer name of fc6_L2 in face_train_test.prototxt.

**Comment by happynear** [comment]
"fc6" is the blob name. "fc6_L2" is the layer name. When extracting features, we need to extract from a blob, not a layer.

**Comment by Lin427** [comment]
Sorry, I don't know caffe well enough. You mean, fc6 is already defined in the caffe file, right?

**Comment by Lin427** [comment]
Thank you, I understand what you mean.
