### ISSUE TITLE
support caffe.binding?

### ISSUE THREAD

**Issue by goxiaobu** [happynear/AMSoftmax#4]
Great work, appreciate it. Can I use the same caffe.binding project without any modification?

**Comment by happynear** [comment]
Sure, caffe.binding is just a dll for easy deployment. You can use it to do the inference of any kinds of networks.

**Comment by goxiaobu** [comment]
Thanks a lot~I have tried your MTCNN project, which applied the caffe.binding dll,and get very good results,appreciate it. Can you provide a similar project which support the AMSoftmax model?

**Comment by happynear** [comment]
Maybe next month during Chinese New Year I would develop one. Now I don't have time to do it.
