### ISSUE TITLE
Setting of deploy

### ISSUE THREAD

**Issue by banxia1994** [happynear/AMSoftmax#5]
Should we save the norm1 layer for deploy? or just get the output from fc5.

**Comment by happynear** [comment]
Here is an example of deployment.
https://github.com/happynear/AMSoftmax/blob/master/prototxt/face_deploy_mirror_normalize.prototxt

I apply the [mirror face trick](https://github.com/happynear/NormFace/blob/master/MirrorFace.md) and normalization inside the network. These two operations are implemented using CUDA, so the speed is faster than doing them outside on CPU.

**Comment by banxia1994** [comment]
thx

**Comment by banxia1994** [comment]
Hi, i  trained AMsoftmax with webface which including 10572 subjects, get the accuracy 99.27% when the deploy file without norm1 layer in LFW, and  get the accuracy 60% with norm1 layer. but In your example of deploy add the norm layer and some tricks, am i missed something in valid process? or some wrong with my valid code?(not your code)

**Comment by happynear** [comment]
It's weird. The normalize layer just does what it should do: normalization, which you would also do during testing. Maybe you need to check your codes...

**Comment by banxia1994** [comment]
[https://github.com/happynear/FaceVerification/blob/master/test_lfw.m](url) Is this your test code?

**Comment by banxia1994** [comment]
sorry to bother you again, Have you released your test code in LFW? thx kindly!

**Comment by happynear** [comment]
We use the same network architecture as SphereFace. You may use SphereFace's experimental settings.
