### ISSUE TITLE
face_train_test_wo_fn.prototxt

### ISSUE THREAD

**Issue by dajidali010** [happynear/AMSoftmax#9]
不好意思，打扰啦

**Comment by happynear** [comment]
不用编辑，其实你猜对了，具体代码在这里：
https://github.com/happynear/caffe-windows/blob/experiment/src/caffe/layers/label_specific_margin.cu

**Comment by happynear** [comment]
这些实验我之前其实都做过了，只是挑了最简单效果最好的一种发表了而已。

**Comment by gangliu123** [comment]
你好我看你跑通了文字添加的那个项目，有些问题想跟你请教可以吗，我的qq：1174810411.谢谢

**Comment by leiyu1980** [comment]
这是在说什么呢？
